name: OpenTelemetry Collector
description: This add-on runs OpenTelemetry Collector.
version: v1.0.6
slug: opentelemetry_collector
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
map:
  - type: addon_config
    read_only: True
    path: /etc/otelcol-contrib/
journald: true
docker_api: true
